version: '3.8'

services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      # Replace with your actual API keys
      GEMINI_API_KEY: "your_gemini_api_key"
      OCR_SPACE_API_KEY: "your_ocr_space_api_key"
    restart: always
